### ISSUE TITLE
Enum values typization is not working

### ISSUE THREAD

**Issue by NikitaYVolkov** [bameyrick/enum-keys-values-entries#3]
#### Actual result
Given any enum, let's say:
```
enum TrafficLight {
    Stop,
    Caution,
    Proceed,
}
```
Any available function will not pick up the type of enum values, in this case it's `TrafficLight` that extends `number`, and will instead treat value type as `unknown`. As IDE hint shows this:
```
(property) keys: <unknown>(_enum: any) => string[]
(property) values: <unknown>(_enum: any) => unknown[]
(property) entries: <unknown>(_enum: any) => [string, unknown][]
```
#### Expected result
When the `Enum.values(TrafficLight)` function is used I expect result to be of type `TrafficLight[]` immediately, without the need to convert `unknown[]` to `TrafficLight[]`, and I expect type exception when assigning these values to `string[]`:
```
const stringArrayVariable: string[] = Enum.values(TrafficLight)
```

**Comment by bameyrick** [comment]
Hi @NikitaYVolkov, thanks for spotting this bug. It should now be fixed in [version 1.0.5 ](https://github.com/bameyrick/enum-keys-values-entries/releases/tag/1.0.5).
